Assignment4: Assignment4.cpp CommunicationNetwork.o
	g++ -std=c++11 -o Assignment4 Assignment4.cpp CommunicationNetwork.o

CommunicationNetwork.o: CommunicationNetwork.cpp CommunicationNetwork.h
	g++ -std=c++11 -c CommunicationNetwork.cpp